export const CARD_LIBRARY = {
  strike: {
    id: "strike",
    name: "Strike",
    cost: 1,
    text: "Deal 6 damage.",
    effects: [{ type: "damage", value: 6 }],
  },
  heavy_strike: {
    id: "heavy_strike",
    name: "Heavy Strike",
    cost: 2,
    text: "Deal 11 damage.",
    effects: [{ type: "damage", value: 11 }],
  },
  guard: {
    id: "guard",
    name: "Guard",
    cost: 1,
    text: "Gain 6 block.",
    effects: [{ type: "block", value: 6 }],
  },
  fortify: {
    id: "fortify",
    name: "Fortify",
    cost: 2,
    text: "Gain 11 block.",
    effects: [{ type: "block", value: 11 }],
  },
  jab: {
    id: "jab",
    name: "Jab",
    cost: 0,
    text: "Deal 3 damage.",
    effects: [{ type: "damage", value: 3 }],
  },
  focus: {
    id: "focus",
    name: "Focus",
    cost: 1,
    text: "Draw 2 cards.",
    effects: [{ type: "draw", value: 2 }],
  },
  ration: {
    id: "ration",
    name: "Ration",
    cost: 1,
    text: "Heal 4 HP.",
    effects: [{ type: "heal", value: 4 }],
  },
  assault: {
    id: "assault",
    name: "Assault",
    cost: 1,
    text: "Deal 8 damage. Lose 2 block.",
    effects: [
      { type: "damage", value: 8 },
      { type: "self_block", value: -2 },
    ],
  },
  tactic: {
    id: "tactic",
    name: "Tactic",
    cost: 0,
    text: "Gain 1 energy.",
    effects: [{ type: "energy", value: 1 }],
  },
  poison_dart: {
    id: "poison_dart",
    name: "Poison Dart",
    cost: 1,
    text: "Apply 3 Poison.",
    effects: [{ type: "status", target: "enemy", status: "poison", value: 3 }],
  },
  expose: {
    id: "expose",
    name: "Expose",
    cost: 1,
    text: "Apply 2 Vulnerable.",
    effects: [{ type: "status", target: "enemy", status: "vulnerable", value: 2 }],
  },
  rally: {
    id: "rally",
    name: "Rally",
    cost: 1,
    text: "Gain 1 Strength.",
    effects: [{ type: "status", target: "player", status: "strength", value: 1 }],
  },
};

export const STARTER_DECK = [
  "strike",
  "strike",
  "strike",
  "heavy_strike",
  "guard",
  "guard",
  "guard",
  "fortify",
  "jab",
  "focus",
  "focus",
  "ration",
  "assault",
  "tactic",
  "poison_dart",
  "poison_dart",
  "expose",
  "expose",
  "rally",
  "rally",
];
