export const CARD_LIBRARY = {
  strike: {
    id: "strike",
    name: "Strike",
    cost: 1,
    text: "Deal 6 damage.",
    effects: [{ type: "damage", value: 6 }],
  },
  heavy_strike: {
    id: "heavy_strike",
    name: "Heavy Strike",
    cost: 2,
    text: "Deal 12 damage.",
    effects: [{ type: "damage", value: 12 }],
  },
  guard: {
    id: "guard",
    name: "Guard",
    cost: 1,
    text: "Gain 6 block.",
    effects: [{ type: "block", value: 6 }],
  },
  fortify: {
    id: "fortify",
    name: "Fortify",
    cost: 2,
    text: "Gain 11 block.",
    effects: [{ type: "block", value: 11 }],
  },
  jab: {
    id: "jab",
    name: "Jab",
    cost: 0,
    text: "Deal 3 damage.",
    effects: [{ type: "damage", value: 3 }],
  },
  focus: {
    id: "focus",
    name: "Focus",
    cost: 1,
    text: "Draw 2 cards.",
    effects: [{ type: "draw", value: 2 }],
  },
  ration: {
    id: "ration",
    name: "Ration",
    cost: 1,
    text: "Heal 4 HP.",
    effects: [{ type: "heal", value: 4 }],
  },
  assault: {
    id: "assault",
    name: "Assault",
    cost: 1,
    text: "Deal 8 damage. Lose 2 block.",
    effects: [
      { type: "damage", value: 8 },
      { type: "self_block", value: -2 },
    ],
  },
  tactic: {
    id: "tactic",
    name: "Tactic",
    cost: 0,
    text: "Gain 1 energy.",
    effects: [{ type: "energy", value: 1 }],
  },
  barrier: {
    id: "barrier",
    name: "Barrier",
    cost: 1,
    text: "Gain 8 block.",
    effects: [{ type: "block", value: 8 }],
  },
  combo: {
    id: "combo",
    name: "Combo",
    cost: 1,
    text: "Deal 4 damage twice.",
    effects: [
      { type: "damage", value: 4 },
      { type: "damage", value: 4 },
    ],
  },
  meditate: {
    id: "meditate",
    name: "Meditate",
    cost: 1,
    text: "Gain 4 block and draw 1.",
    effects: [
      { type: "block", value: 4 },
      { type: "draw", value: 1 },
    ],
  },
};

export const STARTER_DECK = [
  "strike",
  "strike",
  "strike",
  "strike",
  "heavy_strike",
  "guard",
  "guard",
  "guard",
  "fortify",
  "jab",
  "jab",
  "focus",
  "focus",
  "ration",
  "assault",
  "tactic",
  "barrier",
  "barrier",
  "combo",
  "meditate",
];
