export const EXTRA_STORY_EVENTS = {
  delivery_night_shift: {
    id: "delivery_night_shift",
    title: "夜班跑单",
    text: "你接到一段夜班跑单机会，收益不错但体力消耗明显。",
    nodeType: "battle",
    enemyPool: ["scavenger", "sniper"],
    preEffects: { bias: [{ tag: "survival", delta: 1 }] },
    runtimeEffects: { playerHpDelta: -1 },
    branches: [
      {
        id: "delivery_take",
        label: "接下夜班",
        text: "你决定靠时间换现金。",
        effects: { setFlags: ["night_shift"], bias: [{ tag: "debt", delta: 1 }], rewardBias: [{ tag: "survival", delta: 2 }] },
      },
      {
        id: "delivery_skip",
        label: "维持作息",
        text: "你选择拒绝，留出恢复空间。",
        effects: { setFlags: ["sleep_first"], bias: [{ tag: "survival", delta: 1 }], rewardBias: [{ tag: "defense", delta: 2 }] },
      },
    ],
    tags: ["career", "survival"],
  },
  office_politics: {
    id: "office_politics",
    title: "办公室站队",
    text: "团队内部关系紧张，你被迫在中立与站队之间做选择。",
    nodeType: "battle",
    enemyPool: ["enforcer", "sniper"],
    runtimeEffects: { playerHpDelta: -1 },
    branches: [
      {
        id: "office_neutral",
        label: "保持中立",
        text: "你压住观点，降低短期冲突。",
        effects: { setFlags: ["office_neutral"], rewardBias: [{ tag: "utility", delta: 2 }] },
      },
      {
        id: "office_side",
        label: "明确站队",
        text: "你押注其中一方，赌一个更快机会。",
        effects: { setFlags: ["office_side"], bias: [{ tag: "risk", delta: 1 }], rewardBias: [{ tag: "attack", delta: 2 }] },
      },
    ],
    tags: ["career", "social"],
  },
  landlord_inspection: {
    id: "landlord_inspection",
    title: "房东突击检查",
    text: "房东临时说要上门检查，居住压力再次上升。",
    nodeType: "battle",
    enemyPool: ["enforcer", "scavenger"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["rent", "pressure"],
  },
  subway_incident: {
    id: "subway_incident",
    title: "地铁小冲突",
    text: "通勤途中发生小冲突，情绪和时间都被拖住。",
    nodeType: "battle",
    enemyPool: ["scavenger", "sniper"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["social", "survival"],
  },
  viral_meme_backfire: {
    id: "viral_meme_backfire",
    title: "梗图反噬",
    text: "你发的梗图被过度解读，流量反向冲击到现实。",
    nodeType: "battle",
    enemyPool: ["sniper"],
    branches: [
      {
        id: "meme_delete",
        label: "删帖止损",
        text: "你选择快速止损，降低后续风险。",
        effects: { setFlags: ["meme_delete"], rewardBias: [{ tag: "survival", delta: 1 }] },
      },
      {
        id: "meme_hold",
        label: "坚持不删",
        text: "你决定扛住争议，赌一波转化。",
        effects: { setFlags: ["meme_hold"], bias: [{ tag: "risk", delta: 2 }], rewardBias: [{ tag: "attack", delta: 1 }] },
      },
    ],
    tags: ["tieba", "social"],
  },
  budget_spreadsheet: {
    id: "budget_spreadsheet",
    title: "月度预算表",
    text: "你终于把收支摊开在表格上，发现关键缺口比想象更大。",
    nodeType: "battle",
    enemyPool: ["enforcer"],
    preEffects: { bias: [{ tag: "debt", delta: 1 }] },
    runtimeEffects: { playerHpDelta: 1 },
    tags: ["debt", "survival"],
  },
  temp_contract_offer: {
    id: "temp_contract_offer",
    title: "短约外包机会",
    text: "一个短期外包机会出现，节奏很紧但能补现金流。",
    nodeType: "battle",
    enemyPool: ["sniper", "enforcer"],
    branches: [
      {
        id: "contract_accept",
        label: "接短约",
        text: "你决定换现金优先。",
        effects: { setFlags: ["contract_accept"], rewardBias: [{ tag: "career", delta: 2 }] },
      },
      {
        id: "contract_refuse",
        label: "拒绝短约",
        text: "你选择保留长期节奏。",
        effects: { setFlags: ["contract_refuse"], rewardBias: [{ tag: "survival", delta: 2 }] },
      },
    ],
    tags: ["career", "risk"],
  },
  community_group_conflict: {
    id: "community_group_conflict",
    title: "群聊站队升级",
    text: "社区群里争论升级，你被点名要求表态。",
    nodeType: "battle",
    enemyPool: ["sniper", "scavenger"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["social", "tieba"],
  },
  fake_friend_referral: {
    id: "fake_friend_referral",
    title: "熟人内推陷阱",
    text: "熟人说能内推，但条件越来越奇怪。",
    nodeType: "battle",
    enemyPool: ["enforcer", "scavenger"],
    branches: [
      {
        id: "referral_trust",
        label: "先信一次",
        text: "你抱着侥幸相信熟人。",
        effects: { setFlags: ["referral_trust"], bias: [{ tag: "risk", delta: 2 }], rewardBias: [{ tag: "attack", delta: 1 }] },
      },
      {
        id: "referral_verify",
        label: "先做背调",
        text: "你决定先核实信息来源。",
        effects: { setFlags: ["referral_verify"], rewardBias: [{ tag: "utility", delta: 2 }] },
      },
    ],
    tags: ["career", "social"],
  },
  side_project_bug: {
    id: "side_project_bug",
    title: "副项目爆雷",
    text: "周末副项目在关键时刻爆雷，你必须救火。",
    nodeType: "battle",
    enemyPool: ["sniper", "enforcer"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["career", "risk"],
  },
  emergency_hospital_bill: {
    id: "emergency_hospital_bill",
    title: "突发医疗支出",
    text: "突发医疗支出压缩了本月所有计划。",
    nodeType: "battle",
    enemyPool: ["enforcer"],
    runtimeEffects: { playerHpDelta: -2 },
    preEffects: { bias: [{ tag: "debt", delta: 2 }] },
    tags: ["debt", "survival"],
  },
  ai_replacement_panic: {
    id: "ai_replacement_panic",
    title: "AI 替代焦虑",
    text: "行业讨论突然转向“替代”，你不得不重新评估技能路线。",
    nodeType: "battle",
    enemyPool: ["sniper", "enforcer"],
    branches: [
      {
        id: "ai_upskill",
        label: "补技能",
        text: "你选择投入学习。",
        effects: { setFlags: ["ai_upskill"], rewardBias: [{ tag: "career", delta: 2 }] },
      },
      {
        id: "ai_wait",
        label: "先观望",
        text: "你选择先观望，保留精力。",
        effects: { setFlags: ["ai_wait"], rewardBias: [{ tag: "survival", delta: 1 }] },
      },
    ],
    tags: ["career", "pressure"],
  },
  rent_room_ad: {
    id: "rent_room_ad",
    title: "低价租房广告",
    text: "你看到一个离谱低价房源，条件看起来并不真实。",
    nodeType: "battle",
    enemyPool: ["scavenger", "sniper"],
    tags: ["rent", "risk"],
  },
  black_friday_trap: {
    id: "black_friday_trap",
    title: "促销囤货诱惑",
    text: "平台推送限时促销，理性和冲动正在拉扯。",
    nodeType: "battle",
    enemyPool: ["scavenger"],
    branches: [
      {
        id: "sale_control",
        label: "只买必需",
        text: "你控制住消费欲。",
        effects: { setFlags: ["sale_control"], rewardBias: [{ tag: "defense", delta: 1 }] },
      },
      {
        id: "sale_overbuy",
        label: "先买再说",
        text: "你决定趁活动多囤一些。",
        effects: { setFlags: ["sale_overbuy"], bias: [{ tag: "debt", delta: 1 }], playerHpDelta: -1 },
      },
    ],
    tags: ["debt", "tieba"],
  },
  group_buy_scam: {
    id: "group_buy_scam",
    title: "拼团翻车",
    text: "拼团订单突然异常，客服和商家都在踢皮球。",
    nodeType: "battle",
    enemyPool: ["sniper", "scavenger"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["debt", "social"],
  },
  layoffs_forum_post: {
    id: "layoffs_forum_post",
    title: "匿名爆料帖",
    text: "论坛匿名帖又爆新料，你的焦虑被再次点燃。",
    nodeType: "battle",
    enemyPool: ["sniper", "enforcer"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["career", "tieba"],
  },
  overtime_competition: {
    id: "overtime_competition",
    title: "加班内卷赛",
    text: "团队隐性要求加班，你不跟就可能掉队。",
    nodeType: "battle",
    enemyPool: ["enforcer"],
    branches: [
      {
        id: "overtime_join",
        label: "跟进加班",
        text: "你选择跟上节奏。",
        effects: { setFlags: ["overtime_join"], playerHpDelta: -1, rewardBias: [{ tag: "attack", delta: 1 }] },
      },
      {
        id: "overtime_refuse",
        label: "拒绝内卷",
        text: "你选择守住边界。",
        effects: { setFlags: ["overtime_refuse"], rewardBias: [{ tag: "survival", delta: 2 }] },
      },
    ],
    tags: ["career", "health"],
  },
  refund_dispute: {
    id: "refund_dispute",
    title: "退款拉扯",
    text: "你在退款流程里来回拉扯，时间和情绪都被消耗。",
    nodeType: "battle",
    enemyPool: ["scavenger", "sniper"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["debt", "social"],
  },
  neighborhood_noise_war: {
    id: "neighborhood_noise_war",
    title: "邻里噪音战",
    text: "邻里噪音纠纷升级，休息质量持续下降。",
    nodeType: "battle",
    enemyPool: ["scavenger", "enforcer"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["rent", "health"],
  },
  pet_medical_expense: {
    id: "pet_medical_expense",
    title: "宠物医疗账单",
    text: "宠物突发问题，情感与现金流一起承压。",
    nodeType: "battle",
    enemyPool: ["enforcer"],
    runtimeEffects: { playerHpDelta: -1 },
    preEffects: { bias: [{ tag: "debt", delta: 1 }] },
    tags: ["debt", "social"],
  },
  second_hand_market_flip: {
    id: "second_hand_market_flip",
    title: "二手倒卖尝试",
    text: "你尝试做一单二手倒卖，收益和风险都不确定。",
    nodeType: "battle",
    enemyPool: ["scavenger", "sniper"],
    branches: [
      {
        id: "flip_small",
        label: "小额试单",
        text: "你决定小额试水。",
        effects: { setFlags: ["flip_small"], rewardBias: [{ tag: "utility", delta: 1 }] },
      },
      {
        id: "flip_allin",
        label: "重仓一把",
        text: "你决定压一把快钱。",
        effects: { setFlags: ["flip_allin"], bias: [{ tag: "risk", delta: 2 }], playerHpDelta: -1 },
      },
    ],
    tags: ["tieba", "risk"],
  },
  interview_ghosted: {
    id: "interview_ghosted",
    title: "面试后失联",
    text: "面试后对方失联，你的预期再次被打断。",
    nodeType: "battle",
    enemyPool: ["sniper", "enforcer"],
    runtimeEffects: { playerHpDelta: -1 },
    tags: ["career", "pressure"],
  },
  labor_arbitration_tip: {
    id: "labor_arbitration_tip",
    title: "仲裁经验帖",
    text: "你看到一篇实操经验帖，开始考虑系统化维权。",
    nodeType: "battle",
    enemyPool: ["enforcer"],
    requiresFlags: ["negotiation_path"],
    runtimeEffects: { playerHpDelta: 1 },
    tags: ["career", "survival"],
  },
  burnout_recovery_jog: {
    id: "burnout_recovery_jog",
    title: "夜跑恢复计划",
    text: "你开始尝试夜跑，恢复进度缓慢但稳定。",
    nodeType: "battle",
    enemyPool: ["scavenger"],
    runtimeEffects: { playerHpDelta: 1 },
    tags: ["health", "survival"],
  },
};

export const EXTRA_STORY_DECK = [
  "delivery_night_shift",
  "office_politics",
  "landlord_inspection",
  "subway_incident",
  "viral_meme_backfire",
  "budget_spreadsheet",
  "temp_contract_offer",
  "community_group_conflict",
  "fake_friend_referral",
  "side_project_bug",
  "emergency_hospital_bill",
  "ai_replacement_panic",
  "rent_room_ad",
  "black_friday_trap",
  "group_buy_scam",
  "layoffs_forum_post",
  "overtime_competition",
  "refund_dispute",
  "neighborhood_noise_war",
  "pet_medical_expense",
  "second_hand_market_flip",
  "interview_ghosted",
  "labor_arbitration_tip",
  "burnout_recovery_jog",
];
